import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "./Components/transitionalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Julius Ntale Portfolio App",
  description: "Generated by Julius Peter Ntale, the best software engineer animated portfolio",
  keywords: "Julius Ntale, software engineer, portfolio, web developer, photography, videography",
  author: "Julius Peter Ntale",
  viewport: "width=device-width, initial-scale=1.0",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta name="author" content={metadata.author} />
        <meta name="viewport" content={metadata.viewport} />
        <title>{metadata.title}</title>
      </head>
      <body className={inter.className}>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
